export const quizList = [
  {
    level: 'Low-Level',
    title: "Jin and Younggyu's Dino Adventure",
    content:
      'Once upon a time, in a magical forest, there were two brave friends named Jin and Younggyu. They loved exploring new places and having fun. One sunny day, they decided to visit a special amusement park hidden deep in the forest.\n\nAs they walked through the park, they saw many exciting rides and games. But what caught their eyes was a huge, sparkling gate with an image of a dinosaur on it. "Look, Jin! A dinosaur gate!" said Younggyu with a heart full of excitement.\n\n"Let\'s go inside!" Jin said. They both ran towards the gate and entered a world of dinosaurs. The park was filled with amazing dinosaur statues and even a giant bird that looked like a real pterodactyl flying above them.\n\nSuddenly, they heard a loud roar. From behind a tree, a real dinosaur appeared! It was a friendly dinosaur named Dino. "Hello! I\'m Dino. Welcome to Dino Land!" he said with a big smile.\n\nJin and Younggyu were amazed. "Wow, Dino! Can you show us around?" asked Jin.\n\n"Of course!" said Dino. He led them to a magical salt lake where dinosaurs loved to swim. "This lake is very special. It was made by a kind god who wanted to give us a good place to live."\n\nAs they explored more, they found a hidden school where baby dinosaurs learned about the forest. "This is where we learn to be good dinosaurs," Dino explained.\n\nJust then, a group of naughty dinosaurs appeared and started causing trouble. "We need to stop them!" said Younggyu.\n\nWith courage in their hearts, Jin, Younggyu, and Dino worked together to chase away the naughty dinosaurs. They used their clever minds and strong hearts to protect the park.\n\nAfter the adventure, Dino thanked them. "You both have the heart of a true hero," he said.\n\nJin and Younggyu smiled. "We had so much fun, and we made a new friend," said Jin.\n\nThey waved goodbye to Dino and left the magical forest, promising to return one day for more adventures.\n\nAnd so, Jin and Younggyu\'s action-packed day at the amusement park ended, but their friendship and bravery continued to shine, just like the magical salt lake in Dino Land.',
    finishCount: 0,
    totalCount: 10,
  },
];
